### PR TITLE
Add Makefile

### PR DESCRIPTION
**Pull request by psteyer**
Created a Makefile to help with ease of commands.

### CODE REVIEW

**Comment by psteyer** [comment]
Looks like Javascript has a built-in make file functionality. Under package.json there is a script section that allows us to do the same as a make file. Also noticed that npm run build also seems to have linter functionality that runs and fails at the moment. We basically added  `lint": "./node_modules/.bin/eslint ."` underneath the script section of the package.json

**Comment by psteyer** [comment]
I imagine now that the ci.yaml has to be updated with new and correct `run: ` commands

**Comment by cjmartian** [comment]
I think another issue is that `npm run build` is running a linter that is not giving the same output as the `eslint` linter. Maybe we can just try to get the `npm run build` CI passing and once that's done we can retroactively get a linter that is configured to work the same way as the build. 

Next steps in my opinion are:

1. Close this PR
2. Open and merge a new PR to fix current CI
3. Figure out how we can get a linter to use the same config as the build linter
4. Add `npm run lint` to the CI

**Comment by psteyer** [comment]
Closing the PR and going with the steps mentioned above.

**Pull request closed without merging**
